-- Create test users for demo authentication
-- Note: This requires service role permissions

-- Insert users into auth.users table
INSERT INTO auth.users (
    instance_id,
    id,
    aud,
    role,
    email,
    encrypted_password,
    email_confirmed_at,
    confirmation_sent_at,
    confirmation_token,
    recovery_token,
    email_change_token_new,
    email_change,
    phone,
    phone_confirmed_at,
    phone_change,
    phone_change_token,
    phone_change_sent_at,
    raw_app_meta_data,
    raw_user_meta_data,
    is_super_admin,
    created_at,
    updated_at,
    last_sign_in_at,
    email_change_token_current,
    email_change_confirm_status,
    banned_until,
    reauthentication_token,
    reauthentication_sent_at
) VALUES 
-- Group Admin User
(
    '00000000-0000-0000-0000-000000000000',
    gen_random_uuid(),
    'authenticated',
    'authenticated',
    'contact@demoschool.com',
    crypt('TestLift2024!', gen_salt('bf')),
    NOW(),
    NOW(),
    '',
    '',
    '',
    '',
    NULL,
    NULL,
    '',
    '',
    NULL,
    '{"provider": "email", "providers": ["email"]}',
    '{"name": "Sarah Thompson", "role": "GroupContact"}',
    false,
    NOW(),
    NOW(),
    NULL,
    '',
    0,
    NULL,
    '',
    NULL
),
-- Practitioner User  
(
    '00000000-0000-0000-0000-000000000000',
    gen_random_uuid(),
    'authenticated',
    'authenticated',
    'practitioner@demoschool.com',
    crypt('TestLift2024!', gen_salt('bf')),
    NOW(),
    NOW(),
    '',
    '',
    '',
    '',
    NULL,
    NULL,
    '',
    '',
    NULL,
    '{"provider": "email", "providers": ["email"]}',
    '{"name": "Michael Chen", "role": "Practitioner"}',
    false,
    NOW(),
    NOW(),
    NULL,
    '',
    0,
    NULL,
    '',
    NULL
),
-- Child User
(
    '00000000-0000-0000-0000-000000000000',
    gen_random_uuid(),
    'authenticated',
    'authenticated',
    'testchild@child.local',
    crypt('1234', gen_salt('bf')),
    NOW(),
    NOW(),
    '',
    '',
    '',
    '',
    NULL,
    NULL,
    '',
    '',
    NULL,
    '{"provider": "email", "providers": ["email"]}',
    '{"name": "Emma Davis", "role": "Child"}',
    false,
    NOW(),
    NOW(),
    NULL,
    '',
    0,
    NULL,
    '',
    NULL
);