/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "jxdkwfhsicynyvhkutjm"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4ZGt3ZmhzaWN5bnl2aGt1dGptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MjAxNTAsImV4cCI6MjA3MjI5NjE1MH0.ZuG6MjKYX2FM-WCIhzLyVRXA0x87kFgUvy-LlVM2QwY"